version = 1
test_patterns = [
  "src/**"
]
[[analyzers]]
name = "javascript"
enabled = true
  [analyzers.meta]
  environment = ["nodejs"]
  module_system = "es-modules"
  dialect = "typescript"
  style_guide = "airbnb"
